### ISSUE TITLE
Any way to terminate the supervision?

### ISSUE THREAD

**Issue by raycheung** [replikativ/superv.async#5]
I'm try to `close!` the resulting chan of this:
```
  (go-try S
    (<? S (restarting-supervisor ...)))
```
but it seems this outer chan from the surrounding `go-try` has nothing to do with the inner `restarting-supervisor` such that the supervisor loop would carry on.

This makes my program won't terminate. Is there any way to end it please?

**Comment by raycheung** [comment]
Oh, ignore me please. I messed up the default shutdown hook. Closing this.

**Comment by whilo** [comment]
Ok, if something is confusing, please let me know, then I will try to add more documentation.
